
[film]
resolution = [400, 400]

[camera]
type = "orthographic"
scale = 0.1
position = [-5, 5, 6]
towards = [0.0, 0.07, -0.01]
up = [0, 1, 0]

[model.bunny]
file = "bun_zipper.ply"

[node.floor]
group = true
[node.floor.a]
triangle = [[-0.1, 0, -0.1], [-0.1, 0, 0.1], [0.1, 0, -0.1]]
[node.floor.b]
triangle = [[0.1, 0, -0.1], [-0.1, 0, 0.1], [0.1, 0, 0.1]]

[[world]]
instance = "model.bunny"

