[film]
method = "path"
resolution = [800, 800]
supersampling = 128
global_radiance = 0

[camera]
type = "orthographic"
scale = 3.6
position = [0.0, 21.0879993, 135.740004]
towards = [0.0, 2.10879993, 12.5740004]
up = [0, 1, 0]

[model.sphere]
file = "../sphere.ply"
[material.light1]
type = "emissive"
light = [41.5, 43.2, 45]
[node.light1]
material = "light1"
instance = "model.sphere"
[[world]]
instance = "node.light1"
transform = [["scale", 7.5], ["translate", [34.9, 55.9, -15.35]]]

[material.light2]
type = "emissive"
light = [65, 63.3, 61.5]
[node.light2]
material = "light2"
instance = "model.sphere"
[[world]]
instance = "node.light2"
transform = [["scale", 7.5], ["translate", [-32.9, 55.9, 36.29]]]

[model.bg]
file = "geometry/mesh_00001.ply"
[texture.bg]
type = "checkerboard"
[material.bg]
type = "lambertian"
reflectance = "bg"
[[world]]
instance = "model.bg"
transform = [["scale", 0.213], ["translate", [0, -2, 0]]]

[model.cover]
file = "geometry/mesh_00003.ply"
[texture.cover_tex]
type = "image"
file = "texture/book_pbrt.png"
[texture.bump_tex]
type = "image"
file = "texture/uneven_bump.png"
[material.cover]
type = "lambertian"
reflectance = "cover_tex"

[[world]]
material = "cover"
transform = [
  ["rotate-y", -0.6],
  ["rotate-x", -0.8],
  ["rotate-z", 0.7],
  ["scale", 0.5],
  ["translate", [0, 0.4, 0]]]
instance = "model.cover"

[model.pages]
file = "geometry/mesh_00002.ply"
[texture.pages_tex]
type = "image"
file = "texture/book_pages.png"
[material.pages]
type = "lambertian"
reflectance = "pages_tex"

[[world]]
material = "pages"
transform = [
  ["rotate-y", -0.6],
  ["rotate-x", -0.8],
  ["rotate-z", 0.7],
  ["scale", 0.5],
  ["translate", [0, 0.4, 0]]]
instance = "model.pages"

