
[film]
method = "path"
resolution = [800, 800]
supersampling = 32
global_radiance = 0

[camera]
type = "orthographic"
scale = 0.65
position = [20, 10, 20]
towards = [1.5, -1.01, -2.02]
up = [0, 1, 0]

[model.ganesha]
file = "ganesha.ply"
[texture.paint]
type = "image"
file = "ganesha.png"
[material.paint]
type = "lambertian"
reflectance = "paint"

[[world]]
material = "paint"
transform = [["scale", 0.01]]
instance = "model.ganesha"

[model.sphere]
file = "../sphere.ply"
[material.light]
type = "emissive"
light = [5, 5, 5]
[node.light]
[[world]]
material = "light"
instance = "model.sphere"
transform = [["scale", 8], ["translate", [4, 10, 13]]]


[[world]]
triangle = [[-10, -0.41, -10], [-10, -0.41, 10], [10, -0.41, -10]]
[[world]]
triangle = [[10, -0.41, -10], [-10, -0.41, 10], [10, -0.41, 10]]
