
[film]
method = "path"
resolution = [200, 200]
supersampling = 256
global_radiance = 1

[camera]
type = "orthographic"
scale = 1
position = [-5, 0, 0]
towards = [0, 0, 0]
up = [0, 0, 1]

[model.sphere]
file = "sphere.ply"

[material.white]
type = "lambertian"
reflectance = [1, 1, 1]

[material.light]
type = "emissive"
light = [1, 1, 1]

[[world]]
material = "white"
instance = "model.sphere"
transform = [["scale", 0.5]]

[[world]]
material = "white"
instance = "model.sphere"
transform = [["scale", 10]]

[[world]]
material = "light"
instance = "model.sphere"
transform = [["translate", [-7, 0, 0]]]
