
[film]
method = "path"
resolution = [100, 100]
supersampling = 128
global_radiance = 0
depth = 40

[camera]
type = "orthographic"
scale = 0.5
position = [0, -0.55, 0]
towards = [0.01, -1, 0.001]
up = [0, 0, 1]

[model.sphere]
file = "sphere.ply"

[material.white]
type = "lambertian"
reflectance = 1

[material.light]
type = "emissive"
light = 1


[[world]]
material = "light"
instance = "model.sphere"
transform = [["scale", 0.5]]

[[world]]
material = "white"
instance = "model.sphere"
transform = [["scale", 1]]
