
[film]
method = "path"
resolution = [400, 400]
supersampling = 400
global_radiance = 0

[camera]
type = "orthographic"
scale = 8
position = [-4, -8, 5]
towards = [0, 0, 0]
up = [0, 0, 1]

[model.sphere]
file = "sphere.ply"

[material.light]
type = "emissive"
light = [4, 4, 4]

[node.light]
instance = "model.sphere"
material = "light"

[[world]]
triangle = [[-10, -10, -5], [10, -10, -5], [-10, 10, -5]]
[[world]]
triangle = [[10, -10, -5], [10, 10, -5], [-10, 10, -5]]

[[world]]
instance = "node.light"
transform = [["translate", [4, -3, 0]]]

[[world]]
instance = "node.light"
transform = [["translate", [-2, -2, 0]]]

[[world]]
instance = "node.light"
transform = [["translate", [2, 1, 0]]]

[[world]]
instance = "node.light"
transform = [["translate", [-3, 3, 0]]]


