
[film]
resolution = [100, 100]
depth = 3
supersampling = 1
global_radiance = 1

[camera]
type = "orthographic"
scale = 1
position = [0, -10, 10]
towards = [0, 0, 0]
up = [0, 0, 1]

[node.a]
triangle = [[-1, -1, 0], [1, -1, 0], [0, 1, 0]]

[[world]]
transform = [["rotate-x", -0.7]]
instance = "node.a"

