
[film]
method = "path"
resolution = [400, 400]
supersampling = 128
global_radiance = 0

[camera]
type = "orthographic"
scale = 8
position = [-6, -8, 10]
towards = [0, 5, 3]
up = [0, 0, 1]

[model.sphere]
file = "sphere.ply"

[material.light]
type = "emissive"
light = [1, 1, 1]

[node.light]
instance = "model.sphere"
material = "light"

[node.plate]
group = true
[node.plate.a]
triangle = [[-7, -1, 0], [7, -1, 0], [-7, 1, 0]]
[node.plate.b]
triangle = [[7, -1, 0], [7, 1, 0], [-7, 1, 0]]

[[world]]
triangle = [[-10, -10, 0], [10, -10, 0], [-10, 10, 0]]
[[world]]
triangle = [[10, -10, 0], [10, 10, 0], [-10, 10, 0]]

[[world]]
triangle = [[-10, 10, 0], [10, 10, 0], [-10, 10, 10]]
[[world]]
triangle = [[-10, 10, 10], [10, 10, 0], [10, 10, 10]]

[[world]]
instance = "node.plate"
transform = [["translate", [0, -6, 2]]]
[[world]]
instance = "node.plate"
transform = [["translate", [0, 0, 2]]]
[[world]]
instance = "node.plate"
transform = [["translate", [0, 6, 2]]]

[[world]]
instance = "node.light"
transform = [["scale", 1.6], ["translate", [-6, 7, 6]]]

