
[film]
method = "path"
resolution = [100, 100]
supersampling = 10
global_radiance = 1

[camera]
type = "orthographic"
scale = 2
position = [-5, 5, 5]
towards = [0, 0, 0]
up = [0, 0, 1]


[[world]]
triangle = [[-10, -10, 0], [10, -10, 0], [-10, 10, 0]]
[[world]]
triangle = [[10, -10, 0], [10, 10, 0], [-10, 10, 0]]

