
[film]
method = "path"
resolution = [600, 600]
supersampling = 128
global_radiance = 0

[camera]
type = "orthographic"
scale = 0.9
position = [5, 4, -4]
towards = [0.0, 0.2, 0.1]
up = [0.001, 1, 0]

[material.gold]
type = "glossy"
roughness = 0.2
refraction = [0.16, 0.35, 1.5]
absorption = [4, 2.5, 1.9]
transmission = 0

[material.copper]
type = "glossy"
roughness = 0.1
refraction = [0.271, 0.677, 1.316]
absorption = [3.61, 2.62, 2.29]
transmission = 0

[model.dragon]
file = "dragon.ply"

[material.matte]
type = "lambertian"
reflectance = [0.5, 0.5, 0.5]
[material.air]
type = "specular"
absorption = [0, 0, 0]
refraction = [1, 1, 1]
transmission = [1, 1, 1]
[material.glass]
type = "specular"
absorption = [0, 0, 0]
refraction = [1.5, 1.5, 1.5]
transmission = [1, 1, 1]
[material.diamond]
type = "specular"
absorption = [0, 0, 0]
refraction = [2.4, 2.4, 2.4]
transmission = [1, 1, 1]

[material.same]
type = "coat"
coat = "air"
base = "matte"
weight = 1
[material.glass_air_matte]
type = "coat"
coat = "glass"
base = "same"
weight = 1
[material.diamond_matte]
type = "coat"
coat = "diamond"
base = "matte"
weight = 1

[[world]]
material = "glass_air_matte"
instance = "model.dragon"
transform = [["translate", [-30, 40, 50]], ["scale", 0.01]]
[[world]]
material = "diamond_matte"
instance = "model.dragon"
transform = [["translate", [30, 40, -50]], ["scale", 0.01]]

[[world]]
triangle = [[-10, 0, -10], [-10, 0, 10], [10, 0, -10]]
[[world]]
triangle = [[10, 0, -10], [-10, 0, 10], [10, 0, 10]]

[model.sphere]
file = "../sphere.ply"
[material.light]
type = "emissive"
light = [8, 8, 8]
[[world]]
material = "light"
instance = "model.sphere"
transform = [["scale", 9], ["translate", [6, 24, 1.2]]]

