
[film]
resolution = [600, 600]

[camera]
type = "orthographic"
scale = 1.0
position = [5, 6, -4]
towards = [-0.03, 0.11, 0]
up = [0, 1, 0]

[model.dragon]
file = "dragon.ply"

[[world]]
instance = "model.dragon"
transform = [["scale", 0.01]]

[[world]]
instance = "model.dragon"
transform = [["scale", 0.01],
             ["translate", [-0.4, 0.5, 0.5]],
             ["rotate-z", -0.4]]
