
[film]
method = "path"
resolution = [1000, 1000]
supersampling = 1024
global_radiance = 0

[camera]
type = "orthographic"
scale = 2.2
position = [3, 4, -4]
towards = [0.0, 0.2, 0.1]
up = [0, 1, 0]

[material.light]
type = "emissive"
light = [8, 8, 8]

[material.gold]
type = "glossy"
roughness = 0.25
refraction = [0.16, 0.35, 1.5]
absorption = [4, 2.5, 1.9]

[material.silver]
type = "glossy"
roughness = 0.20
refraction = [0.159, 0.145, 0.135]
absorption = [3.929, 3.19, 2.38]

[material.platinum]
type = "glossy"
roughness = 0.25
refraction = [2.37, 2.08, 1.84]
absorption = [4.26, 3.71, 3.136]

[material.lead]
type = "glossy"
roughness = 0.32
refraction = [1.91, 1.83, 1.44]
absorption = [3.51, 3.4, 3.18]

[material.copper]
type = "glossy"
roughness = 0.22
refraction = [0.271, 0.677, 1.316]
absorption = [3.61, 2.62, 2.29]




[node.overcast]
material = "light"
triangle = [[-1, 0, -1], [1, 0, -1], [-1, 0, 1]]

[model.dragon]
file = "dragon.ply"

[[world]]
instance = "model.dragon"
material = "gold"
transform = [["translate", [0, 40, 0]], ["scale", 0.01]]

[[world]]
instance = "model.dragon"
material = "silver"
transform = [["rotate-y", 1], ["translate", [200, 40, -100]], ["scale", 0.01]]

[[world]]
instance = "model.dragon"
material = "platinum"
transform = [["rotate-y", 2], ["translate", [-100, 40, 200]], ["scale", 0.01]]

[[world]]
instance = "model.dragon"
material = "copper"
transform = [["rotate-y", 5], ["translate", [-200, 40, 40]], ["scale", 0.01]]

[[world]]
instance = "model.dragon"
material = "lead"
transform = [["translate", [200, 40, 100]], ["scale", 0.01], ["rotate-y", 2]]

[[world]]
triangle = [[-10, 0, -10], [-10, 0, 10], [10, 0, -10]]
[[world]]
triangle = [[10, 0, -10], [-10, 0, 10], [10, 0, 10]]

[material.lit]
type = "emissive"
light = [20, 20, 20]

[[world]]
instance = "model.dragon"
material = "lit"
transform = [["rotate-y", 1.2], ["translate", [140, 40, 50]], ["scale", 0.01]]
