
[film]
method = "path"
resolution = [800, 800]
supersampling = 128
global_radiance = 0

[camera]
type = "orthographic"
scale = 1.0
position = [5, 4, -4]
towards = [0.0, 0.2, 0.1]
up = [0, 1, 0]

[material.light]
type = "emissive"
light = [8, 8, 8]

[material.gold]
type = "glossy"
roughness = 0.2
refraction = [0.16, 0.35, 1.5]
absorption = [4, 2.5, 1.9]

[material.copper]
type = "glossy"
roughness = 0.1
refraction = [0.271, 0.677, 1.316]
absorption = [3.61, 2.62, 2.29]

[node.overcast]
material = "light"
triangle = [[-1, 0, -1], [1, 0, -1], [-1, 0, 1]]

[model.dragon]
file = "dragon.ply"

[[world]]
instance = "model.dragon"
material = "gold"
transform = [["translate", [0, 40, 0]], ["scale", 0.01]]

[[world]]
triangle = [[-10, 0, -10], [-10, 0, 10], [10, 0, -10]]
[[world]]
triangle = [[10, 0, -10], [-10, 0, 10], [10, 0, 10]]

[[world]]
instance = "node.overcast"
transform = [["translate", [0.2, 2, 0.1]], ["scale", 12]]
