[film]
method = "path"
resolution = [600, 600]
supersampling = 1024
global_radiance = 0
depth = 24

[camera]
type = "orthographic"
scale = 0.9
position = [5, 4, -4]
towards = [0.0, 0.2, 0.1]
up = [0.001, 1, 0]

[model.sphere]
file = "../sphere.ply"
[material.light]
type = "emissive"
light = [8, 8, 8]
[node.light]
[[world]]
material = "light"
instance = "model.sphere"
transform = [["scale", 9], ["translate", [6, 24, 1.2]]]

[material.glass]
type = "glossy"
absorption = [0, 0, 0]
refraction = [1.5, 1.5, 1.5]
transmission = [1, 1, 1]
roughness = 0.01

[material.rough]
type = "glossy"
absorption = [0, 0, 0]
refraction = [1.5, 1.5, 1.5]
transmission = [1, 1, 1]
roughness = 0.5

[model.dragon]
file = "dragon.ply"

[[world]]
material = "glass"
instance = "model.dragon"
transform = [["translate", [-30, 40, 50]], ["scale", 0.01]]

[[world]]
material = "rough"
instance = "model.dragon"
transform = [["translate", [30, 40, -50]], ["scale", 0.01]]

[[world]]
triangle = [[-10, 0, -10], [-10, 0, 10], [10, 0, -10]]
[[world]]
triangle = [[10, 0, -10], [-10, 0, 10], [10, 0, 10]]

